# Generated by Django 3.2 on 2022-05-10 12:37

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ContactUs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('subject', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='VipPost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(choices=[('Sport', 'Sport'), ('Business', 'Business'), ('Food', 'Food'), ('Tech', 'Tech'), ('Design', 'Design'), ('Travel', 'Travel'), ('Culture', 'Culture'), ('Politics', 'Politics'), ('Celebrity', 'Celebrity'), ('Other', 'Other')], max_length=50)),
                ('description', models.CharField(max_length=500)),
                ('title', models.CharField(max_length=100)),
                ('content', models.TextField()),
                ('date_posted', models.DateTimeField(default=django.utils.timezone.now)),
                ('image', models.ImageField(upload_to='')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(choices=[('Sport', 'Sport'), ('Business', 'Business'), ('Food', 'Food'), ('Tech', 'Tech'), ('Design', 'Design'), ('Travel', 'Travel'), ('Culture', 'Culture'), ('Politics', 'Politics'), ('Celebrity', 'Celebrity'), ('Other', 'Other')], max_length=50)),
                ('description', models.CharField(max_length=500)),
                ('title', models.CharField(max_length=100)),
                ('content', models.TextField()),
                ('date_posted', models.DateTimeField(default=django.utils.timezone.now)),
                ('image', models.ImageField(upload_to='')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
